name: run dbt job on commit

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  run_dbt_cloud_job:
    name: Run dbt Cloud Job
    runs-on: ubuntu-latest

    # Set the environment variables needed for the run
    env:
      DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
      DBT_ACCOUNT_ID: 51798
      DBT_PROJECT_ID: 99481
      DBT_PR_JOB_ID: 85141
      DBT_JOB_BRANCH: ${{ github.ref_name }}
      DBT_JOB_SCHEMA_OVERRIDE: DBT_GITHUB_PIPELINE_$DBT_JOB_BRANCH


    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: Run dbt Cloud job
        run: "python ./.github/workflows/run_and_monitor_dbt_job.py"